Somativa(BOA)/Somativa/Models/Compra.cs
using System.ComponentModel;

namespace Somativa.Models
{
    public class Compra
    {
        public Guid CompraId { get; set; }
        [DisplayName("Nota Fiscal")]
        public int Nota { get; set; }
        [DisplayName("Data e hora")]
        public DateTime DataHora { get; set; }
        public IEnumerable<CompraItem>? CompraItems { get; set; }
    }
}

Somativa(BOA)/Somativa/Controllers/CompraItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class CompraItemsController : Controller
    {
        private readonly SprintContext _context;

        public CompraItemsController(SprintContext context)
        {
            _context = context;
        }

        // GET: CompraItems
        public async Task<IActionResult> Index(Guid Id)
        {
            var sprintContext = _context.CompraItens.Include(c => c.Compra).Include(c => c.Produto);
            ViewData["CompraId"] = Id;
            return View(await sprintContext.Where(i => i.CompraId == Id).ToListAsync());
        }

        // GET: CompraItems/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // GET: CompraItems/Create
        public IActionResult Create(Guid Id)
        {
            //ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "CompraId");            
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            ViewData["CompraId"] = Id;
            return View();
        }

        // POST: CompraItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (ModelState.IsValid)
            {
                compraItem.CompraItemId = Guid.NewGuid();
                _context.Add(compraItem);
                await _context.SaveChangesAsync();

                Produto p = _context.Produtos.Where(p => p.ProdutoId == compraItem.ProdutoId).FirstOrDefault();
                p.Estoque += compraItem.Quantidade;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { Id = compraItem.CompraId });
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem == null)
            {
                return NotFound();
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // POST: CompraItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (id != compraItem.CompraItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compraItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraItemExists(compraItem.CompraItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // POST: CompraItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.CompraItens == null)
            {
                return Problem("Entity set 'SprintContext.CompraItens'  is null.");
            }
            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem != null)
            {
                _context.CompraItens.Remove(compraItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraItemExists(Guid id)
        {
          return (_context.CompraItens?.Any(e => e.CompraItemId == id)).GetValueOrDefault();
        }
    }
}

Somativa(BOA)/Somativa/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class ComprasController : Controller
    {
        private readonly SprintContext _context;

        public ComprasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
              return _context.Compras != null ? 
                          View(await _context.Compras.ToListAsync()) :
                          Problem("Entity set 'SprintContext.Compras'  is null.");
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                compra.CompraId = Guid.NewGuid();
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (id != compra.CompraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.CompraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'SprintContext.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(Guid id)
        {
          return (_context.Compras?.Any(e => e.CompraId == id)).GetValueOrDefault();
        }
    }
}

Somativa(BOA)/Somativa/Views/Compras/Create.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Criar";
}

<div class="row container justify-content-center bg-white bordinha mx-0">
    <div class="col-md-4">
        <h1 class="text-center text-uppercase mt-3">Compra</h1>
        <h2 class="text-center text-uppercase mt-3 text-secondary">Criar</h2>
        <hr />

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nota" class="control-label"></label>
                <input asp-for="Nota" class="form-control" />
                <span asp-validation-for="Nota" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>

            <div class="form-group text-center my-4">
                <input type="submit" value="Criar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Voltar à Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa(BOA)/Somativa/Views/Compras/Delete.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompraId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Somativa(BOA)/Somativa/Views/Compras/Details.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CompraId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Somativa(BOA)/Somativa/Views/Compras/Edit.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Edit";
}

<div class="row container justify-content-center bg-white bordinha mx-0">
    <div class="col-md-4">
        <h1 class="text-center text-uppercase mt-3">Compra</h1>
        <h2 class="text-center text-uppercase mt-3 text-secondary">Editar</h2>

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompraId" />

            <div class="form-group mb-3">
                <label asp-for="Nota" class="control-label"></label>
                <input asp-for="Nota" class="form-control" />
                <span asp-validation-for="Nota" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>

            <div class="form-group text-center my-4">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a asp-action="Index" class="btn btn-secondary ml-2">Voltar à Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa(BOA)/Somativa/Views/Compras/Index.cshtml
@model IEnumerable<Somativa.Models.Compra>

@{
    ViewData["Title"] = "Compras";
}
<partial name="~/Views/Home/_LayoutParcial.cshtml" />

<div class="bg-white container bordinha">
    <h1 class="text-center text-uppercase pt-3">@ViewData["Title"]</h1>

    <div class="table-responsive">
    <table class="table table-striped ">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataHora)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataHora)
                    </td>
                    <td class="d-flex text-end justify-content-end">
                        <a asp-action="Edit" asp-route-id="@item.CompraId" class="aSemLinha pt-25">
                            <svg bootstrap-icon="PencilSquare" width="32" height="32" aria-label="Alarms" class="text-primary"></svg>
                        </a>

                        <button asp-action="Delete" asp-route-id="@item.CompraId" class="btn aSemLinha px-0 pe-sm-2" data-bs-toggle="modal" data-bs-target="#Apagar-@item.CompraId">
                            <svg bootstrap-icon="TrashFill" width="32" height="32" aria-label="Alarms" class="text-danger"></svg>
                        </button>

                        <a asp-controller="CompraItems" asp-action="Index" asp-route-id="@item.CompraId" class="aSemLinha pt-25">
                            <svg bootstrap-icon="List" width="32" height="32" aria-label="Alarms" class="text-secondary"></svg>
                        </a>
                    </td>
                </tr>

                <!-- Modal APAGAR -->
                <div class="modal fade" id="Apagar-@item.CompraId" tabindex="-1" aria-labelledby="ApagarLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3 class="text-center alert alert-danger">Tem certeza que deseja apagar essa Compra?</h3>
                            </div>
                            <div class="modal-body">
                                <div>
                                    <dl class="row text-center">
                                        <dt class="col-sm-4">
                                            @Html.DisplayNameFor(model => model.Nota)
                                        </dt>
                                        <dd class="col-sm-8">
                                            @Html.DisplayFor(model => item.Nota)
                                        </dd>
                                        <dt class="col-sm-4">
                                            @Html.DisplayNameFor(model => model.DataHora)
                                        </dt>
                                        <dd class="col-sm-8">
                                            @Html.DisplayFor(model => item.DataHora)
                                        </dd>
                                        <!-- Add other properties as needed -->
                                    </dl>
                                </div>
                            </div>
                            <div class="modal-footer text-center justify-content-center">
                                <form asp-action="Delete" asp-route-id="@item.CompraId">
                                    <input type="hidden" asp-for="@item.CompraId" />
                                    <input type="submit" value="Delete" class="btn btn-danger" />
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close" asp-action="Index">Voltar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
    </div>
    <div class="text-center pb-3">
        <a asp-action="Create">
            <svg bootstrap-icon="PlusSquareFill" width="32" height="32" aria-label="Alarms" class="text-success"></svg>
        </a>
    </div>
</div>