Somativa(BOA)/Somativa/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class ClientesController : Controller
    {
        private readonly SprintContext _context;

        public ClientesController(SprintContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Clientes != null ? 
                          View(await _context.Clientes.ToListAsync()) :
                          Problem("Entity set 'SprintContext.Clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,Nome,Endereco,Telefone,Cpf,Email,Nascimento")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.ClienteId = Guid.NewGuid();
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ClienteId,Nome,Endereco,Telefone,Cpf,Email,Nascimento")] Cliente cliente)
        {
            if (id != cliente.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'SprintContext.Clientes'  is null.");
            }
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(Guid id)
        {
          return (_context.Clientes?.Any(e => e.ClienteId == id)).GetValueOrDefault();
        }
    }
}

Somativa(BOA)/Somativa/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class ComprasController : Controller
    {
        private readonly SprintContext _context;

        public ComprasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
              return _context.Compras != null ? 
                          View(await _context.Compras.ToListAsync()) :
                          Problem("Entity set 'SprintContext.Compras'  is null.");
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                compra.CompraId = Guid.NewGuid();
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (id != compra.CompraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.CompraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'SprintContext.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(Guid id)
        {
          return (_context.Compras?.Any(e => e.CompraId == id)).GetValueOrDefault();
        }
    }
}

Somativa(BOA)/Somativa/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;
using System.Diagnostics;

namespace Somativa.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SprintContext _context;

        public HomeController(ILogger<HomeController> logger, SprintContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Produtinhos(Guid Id)
        {
            List<Categoria> categs = await _context.Categorias.ToListAsync();
            ViewData["Categorias"] = categs;


            var sprintContext = _context.Produtos.Include(p => p.Categoria).Include(p => p.Fornecedor);

            if (Id != null && !Id.ToString().Equals("00000000-0000-0000-0000-000000000000"))
            {
                return View(await sprintContext.Where(i => i.CategoriaId == Id).ToListAsync());
            }

            return View(await sprintContext.ToListAsync());
        }

        public IActionResult IndexTables()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Somativa(BOA)/Somativa/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class VendasController : Controller
    {
        private readonly SprintContext _context;

        public VendasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Vendas
        public async Task<IActionResult> Index()
        {
            var sprintContext = _context.Vendas.Include(v => v.Cliente);
            return View(await sprintContext.ToListAsync());
        }

        // GET: Vendas/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.VendaId == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // GET: Vendas/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome");
            return View();
        }

        // POST: Vendas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendaId,Nota,ClienteId,DataHora")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                venda.VendaId = Guid.NewGuid();
                _context.Add(venda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // GET: Vendas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas.FindAsync(id);
            if (venda == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // POST: Vendas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VendaId,Nota,ClienteId,DataHora")] Venda venda)
        {
            if (id != venda.VendaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.VendaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // GET: Vendas/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.VendaId == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Vendas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Vendas == null)
            {
                return Problem("Entity set 'SprintContext.Vendas'  is null.");
            }
            var venda = await _context.Vendas.FindAsync(id);
            if (venda != null)
            {
                _context.Vendas.Remove(venda);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaExists(Guid id)
        {
          return (_context.Vendas?.Any(e => e.VendaId == id)).GetValueOrDefault();
        }
    }
}

Somativa(BOA)/Somativa/Views/Home/IndexTables.cshtml
@{
    ViewData["Title"] = "Cards";
}
<partial name="~/Views/Home/_LayoutParcial.cshtml" />

<style>
    body {
        background: linear-gradient(to bottom, #9ccb97, #39676b); /* Substitua as cores conforme necessário */
    }
</style>

<div class="bg-white container bordinha py-5">
    <div class="text-center">
        <p class="fs-64">BEM-VINDO</p>
        <p class="text-secondary fs-24">A ÁREA DE </p>
        <p class="fs-64 fw-bolder">TABELAS</p>
    </div>
</div>

Somativa(BOA)/Somativa/Views/Home/Produtinhos.cshtml
@model IEnumerable<Somativa.Models.Produto>
@{
    ViewData["Title"] = "Produtos";
    List<Categoria> categs = ViewBag.Categorias;
}


<div class=" container d-flex row mx-0 mb-5 mb-sm-0">

    @*CARDS E CATEGORIAS*@

    <div class="flex-column col-md-3">

        <div class="card text-bg-dark mb-5">

            <h4 class="card-header bg-success text-white text-center">Bem-Vindo!</h4>
            <div class="card-body">
                <h5 class="card-subtitle mb-3 text-center">À Floresta Encantada Floricultura!</h5>
                <p class="card-text">
                    Somos apaixonados por transformar sentimentos em flores. Com raízes profundas na natureza, criamos arranjos únicos para todas as ocasiões. Nosso compromisso com a sustentabilidade e serviço personalizado reflete nosso amor pela beleza que a natureza oferece. Visite-nos e deixe a Floresta Negra florescer em sua vida.
                </p>
            </div>

        </div>

        <div class="card text-bg-dark mb-5">

            <h4 class="card-header bg-success text-white text-center">Categorias</h4>
            <div class="card-body text-center">

                @foreach (var item in categs)
                {
                    <p class="card-text ">
                        <a class="text-decoration-none text-black border-1 border-bottom"
                           asp-route-id="@item.CategoriaId">@item.Nome</a>
                    </p>
                }
            </div>

        </div>

    </div>



@*CARROSSEL E PRODUTOS*@

<div class="flex-column col-md-9">
        <div id="carouselExampleIndicators" class="carousel slide">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="6" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="7" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/img/carrossel1.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel2.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel3.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel4.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel5.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel6.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel7.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/img/carrossel.png" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>

    <div class="bg-white py-4">
        <h1 class="text-uppercase text-center bg-success text-white shadow">Principais Itens do Dia</h1>
    </div>


    <div class="d-flex flex-wrap bg-white rounded-2 rounded-bottom pb-4 justify-content-evenly">

        @foreach (var item in Model)
        {
            <div class="card col-5 col-md-4 text-bg-dark mb-2">
                <div class="btn">
                    <div class="card-body">
                        <img src="~/img/@item.Imagem" class="d-block w-100 bordinha" alt="...">
                        <p class="card-text">

                            <div class="fw-bold fs-5 text-decoration-underline">
                                @item.Nome  
                            </div>

                        </p>

                    </div>
                    <p class="fw-bold  shadow">R$@item.Preco</p>

                    
                    <button class="btn btn-success">COMPRAR</button>
                    
                </div>
            </div>
        }
    </div>


</div>

Somativa(BOA)/Somativa/Views/Home/_LayoutParcial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 rounded-pill d-none d-sm-block">
    <div class="container-fluid ">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
            <ul class="navbar-nav flex-grow-1 justify-content-center">

                <li class="nav-item ">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Vendas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="RelatProd">Relatório de produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="RelatMov">Relatório de movimentações</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 rounded-pill d-block d-sm-none">
    <div class="container-fluid px-0 justify-content-center">

        <button class="navbar-toggler btn border-0 px-2 text-black " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbarLayout" aria-controls="offcanvasDarkNavbar">
            TABELAS
        </button>

        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbarLayout" aria-labelledby="offcanvasDarkNavbarLayoutLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLayoutLabel">Tabelas</h5>
                <button type="button" class="btn-close btn-close-black" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex">
                <ul class="navbar-nav justify-content-center flex-grow-1 pe-3 text-end fs-2 ">

                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Vendas</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                    </li>
                    <li class="nav-item border-top border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="RelatProd">Relatório de produtos</a>
                    </li>
                    <li class="nav-item border-top border-bottom border-1">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="RelatMov">Relatório de movimentações</a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</nav>